# Generated by Django 5.0.6 on 2025-10-18 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lose_weight', 'Giảm cân'), ('maintain', 'Duy trì'), ('gain_muscle', 'Tăng cơ'), ('endurance', 'Cải thiện sức bền')], max_length=20)),
                ('target_value', models.FloatField(help_text='Ví dụ: cân nặng mục tiêu (kg) hay số buổi/tuần')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
