# Generated by Django 5.0.6 on 2025-11-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Đang thực hiện'), ('achieved', 'Hoàn thành'), ('paused', 'Tạm dừng'), ('dropped', 'Hủy')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='weight_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='weight_target',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
