# Generated by Django 5.0.6 on 2025-11-24 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_progress_pct_goal_status_goal_weight_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='progress_pct',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='weight_start',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='weight_target',
        ),
        migrations.AddField(
            model_name='goal',
            name='daily_calorie_target_in',
            field=models.FloatField(blank=True, help_text='Calo nên nạp mỗi ngày để đạt mục tiêu', null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='daily_calorie_target_out',
            field=models.FloatField(blank=True, help_text='Calo nên đốt mỗi ngày để đạt mục tiêu', null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_weight_kg',
            field=models.FloatField(blank=True, help_text='Cân nặng khi bắt đầu mục tiêu (kg)', null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('failed', 'Không hoàn thành')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_value',
            field=models.FloatField(help_text='Cân nặng mục tiêu (kg)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('lose_weight', 'Giảm cân'), ('gain_weight', 'Tăng cân'), ('maintain', 'Duy trì')], max_length=20),
        ),
    ]
