# Generated by Django 5.0.6 on 2025-11-24 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_options_remove_goal_progress_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
