# Generated by Django 5.0.6 on 2025-10-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Ít vận động (x1.2)'), ('light', 'Nhẹ (x1.375)'), ('moderate', 'Vừa (x1.55)'), ('active', 'Nhiều (x1.725)'), ('very', 'Rất nhiều (x1.9)')], default='light', max_length=10),
        ),
    ]
