# Generated by Django 5.0.6 on 2025-10-18 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Sáng'), ('lunch', 'Trưa'), ('dinner', 'Tối'), ('snack', 'Ăn nhẹ')], max_length=20)),
                ('food', models.CharField(max_length=200)),
                ('portion', models.CharField(blank=True, max_length=100)),
                ('calories_in', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('run', 'Chạy bộ'), ('walk', 'Đi bộ'), ('bike', 'Đạp xe'), ('gym', 'Gym'), ('yoga', 'Yoga')], max_length=10)),
                ('duration_min', models.PositiveIntegerField(default=30)),
                ('distance_km', models.FloatField(default=0.0)),
                ('steps', models.IntegerField(default=0)),
                ('calories_out', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
