# Generated by Django 5.0.6 on 2025-11-23 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_workout_note_alter_meal_date_alter_workout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('calories_per_100g', models.FloatField(help_text='kcal trên 100g')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='quantity_gram',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories_in',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.food'),
        ),
    ]
